//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.18 at 12:12:25 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bank.project.soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soap.project.bank;
